package com.server.db.dao;

import com.server.db.model.OrderRecord;
import com.server.db.model.OrderRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderRecordMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    int countByExample(OrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    int deleteByExample(OrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    int insert(OrderRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    int insertSelective(OrderRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    List<OrderRecord> selectByExample(OrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    OrderRecord selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderRecord record, @Param("example") OrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderRecord record, @Param("example") OrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderRecord record);
}