package com.server.db.dao;

import com.server.db.model.ProductRecord;
import com.server.db.model.ProductRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductRecordMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_product
     * @mbggenerated
     */
    int countByExample(ProductRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_product
     * @mbggenerated
     */
    int deleteByExample(ProductRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_product
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_product
     * @mbggenerated
     */
    int insert(ProductRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_product
     * @mbggenerated
     */
    int insertSelective(ProductRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_product
     * @mbggenerated
     */
    List<ProductRecord> selectByExample(ProductRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_product
     * @mbggenerated
     */
    ProductRecord selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_product
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductRecord record, @Param("example") ProductRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_product
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductRecord record, @Param("example") ProductRecordExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_product
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_product
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductRecord record);
}