package com.server.db.model;

public class OrderRecord {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.uid
     * @mbggenerated
     */
    private Long uid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.orderId
     * @mbggenerated
     */
    private Long orderId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.channelId
     * @mbggenerated
     */
    private String channelId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.serverId
     * @mbggenerated
     */
    private String serverId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.userId
     * @mbggenerated
     */
    private String userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.roleId
     * @mbggenerated
     */
    private String roleId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.productId
     * @mbggenerated
     */
    private String productId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.productAmount
     * @mbggenerated
     */
    private Integer productAmount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.productNum
     * @mbggenerated
     */
    private Integer productNum;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.virtualCurrency
     * @mbggenerated
     */
    private Integer virtualCurrency;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.orderInfo
     * @mbggenerated
     */
    private String orderInfo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.orderExt
     * @mbggenerated
     */
    private String orderExt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.orderState
     * @mbggenerated
     */
    private Integer orderState;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.createTime
     * @mbggenerated
     */
    private Long createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.dispatchState
     * @mbggenerated
     */
    private Integer dispatchState;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.dispatchTime
     * @mbggenerated
     */
    private Long dispatchTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.dispatchCount
     * @mbggenerated
     */
    private Integer dispatchCount;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.nextDispatchTime
     * @mbggenerated
     */
    private Long nextDispatchTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.paydes
     * @mbggenerated
     */
    private String paydes;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.uid
     * @return  the value of t_order.uid
     * @mbggenerated
     */
    public Long getUid() {
	return uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.uid
     * @param uid  the value for t_order.uid
     * @mbggenerated
     */
    public void setUid(Long uid) {
	this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.orderId
     * @return  the value of t_order.orderId
     * @mbggenerated
     */
    public Long getOrderId() {
	return orderId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.orderId
     * @param orderId  the value for t_order.orderId
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
	this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.channelId
     * @return  the value of t_order.channelId
     * @mbggenerated
     */
    public String getChannelId() {
	return channelId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.channelId
     * @param channelId  the value for t_order.channelId
     * @mbggenerated
     */
    public void setChannelId(String channelId) {
	this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.serverId
     * @return  the value of t_order.serverId
     * @mbggenerated
     */
    public String getServerId() {
	return serverId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.serverId
     * @param serverId  the value for t_order.serverId
     * @mbggenerated
     */
    public void setServerId(String serverId) {
	this.serverId = serverId == null ? null : serverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.userId
     * @return  the value of t_order.userId
     * @mbggenerated
     */
    public String getUserId() {
	return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.userId
     * @param userId  the value for t_order.userId
     * @mbggenerated
     */
    public void setUserId(String userId) {
	this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.roleId
     * @return  the value of t_order.roleId
     * @mbggenerated
     */
    public String getRoleId() {
	return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.roleId
     * @param roleId  the value for t_order.roleId
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
	this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.productId
     * @return  the value of t_order.productId
     * @mbggenerated
     */
    public String getProductId() {
	return productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.productId
     * @param productId  the value for t_order.productId
     * @mbggenerated
     */
    public void setProductId(String productId) {
	this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.productAmount
     * @return  the value of t_order.productAmount
     * @mbggenerated
     */
    public Integer getProductAmount() {
	return productAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.productAmount
     * @param productAmount  the value for t_order.productAmount
     * @mbggenerated
     */
    public void setProductAmount(Integer productAmount) {
	this.productAmount = productAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.productNum
     * @return  the value of t_order.productNum
     * @mbggenerated
     */
    public Integer getProductNum() {
	return productNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.productNum
     * @param productNum  the value for t_order.productNum
     * @mbggenerated
     */
    public void setProductNum(Integer productNum) {
	this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.virtualCurrency
     * @return  the value of t_order.virtualCurrency
     * @mbggenerated
     */
    public Integer getVirtualCurrency() {
	return virtualCurrency;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.virtualCurrency
     * @param virtualCurrency  the value for t_order.virtualCurrency
     * @mbggenerated
     */
    public void setVirtualCurrency(Integer virtualCurrency) {
	this.virtualCurrency = virtualCurrency;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.orderInfo
     * @return  the value of t_order.orderInfo
     * @mbggenerated
     */
    public String getOrderInfo() {
	return orderInfo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.orderInfo
     * @param orderInfo  the value for t_order.orderInfo
     * @mbggenerated
     */
    public void setOrderInfo(String orderInfo) {
	this.orderInfo = orderInfo == null ? null : orderInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.orderExt
     * @return  the value of t_order.orderExt
     * @mbggenerated
     */
    public String getOrderExt() {
	return orderExt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.orderExt
     * @param orderExt  the value for t_order.orderExt
     * @mbggenerated
     */
    public void setOrderExt(String orderExt) {
	this.orderExt = orderExt == null ? null : orderExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.orderState
     * @return  the value of t_order.orderState
     * @mbggenerated
     */
    public Integer getOrderState() {
	return orderState;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.orderState
     * @param orderState  the value for t_order.orderState
     * @mbggenerated
     */
    public void setOrderState(Integer orderState) {
	this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.createTime
     * @return  the value of t_order.createTime
     * @mbggenerated
     */
    public Long getCreateTime() {
	return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.createTime
     * @param createTime  the value for t_order.createTime
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
	this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.dispatchState
     * @return  the value of t_order.dispatchState
     * @mbggenerated
     */
    public Integer getDispatchState() {
	return dispatchState;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.dispatchState
     * @param dispatchState  the value for t_order.dispatchState
     * @mbggenerated
     */
    public void setDispatchState(Integer dispatchState) {
	this.dispatchState = dispatchState;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.dispatchTime
     * @return  the value of t_order.dispatchTime
     * @mbggenerated
     */
    public Long getDispatchTime() {
	return dispatchTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.dispatchTime
     * @param dispatchTime  the value for t_order.dispatchTime
     * @mbggenerated
     */
    public void setDispatchTime(Long dispatchTime) {
	this.dispatchTime = dispatchTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.dispatchCount
     * @return  the value of t_order.dispatchCount
     * @mbggenerated
     */
    public Integer getDispatchCount() {
	return dispatchCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.dispatchCount
     * @param dispatchCount  the value for t_order.dispatchCount
     * @mbggenerated
     */
    public void setDispatchCount(Integer dispatchCount) {
	this.dispatchCount = dispatchCount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.nextDispatchTime
     * @return  the value of t_order.nextDispatchTime
     * @mbggenerated
     */
    public Long getNextDispatchTime() {
	return nextDispatchTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.nextDispatchTime
     * @param nextDispatchTime  the value for t_order.nextDispatchTime
     * @mbggenerated
     */
    public void setNextDispatchTime(Long nextDispatchTime) {
	this.nextDispatchTime = nextDispatchTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.paydes
     * @return  the value of t_order.paydes
     * @mbggenerated
     */
    public String getPaydes() {
	return paydes;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.paydes
     * @param paydes  the value for t_order.paydes
     * @mbggenerated
     */
    public void setPaydes(String paydes) {
	this.paydes = paydes == null ? null : paydes.trim();
    }
}