package com.server.db.model;

import java.util.ArrayList;
import java.util.List;

public class OrderRecordExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_order
     * @mbggenerated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_order
     * @mbggenerated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_order
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    public OrderRecordExample() {
	oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
	this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    public String getOrderByClause() {
	return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
	this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    public boolean isDistinct() {
	return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
	return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    public void or(Criteria criteria) {
	oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    public Criteria or() {
	Criteria criteria = createCriteriaInternal();
	oredCriteria.add(criteria);
	return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    public Criteria createCriteria() {
	Criteria criteria = createCriteriaInternal();
	if (oredCriteria.size() == 0) {
	    oredCriteria.add(criteria);
	}
	return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
	Criteria criteria = new Criteria();
	return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
     * @mbggenerated
     */
    public void clear() {
	oredCriteria.clear();
	orderByClause = null;
	distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_order
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
	protected List<Criterion> criteria;

	protected GeneratedCriteria() {
	    super();
	    criteria = new ArrayList<Criterion>();
	}

	public boolean isValid() {
	    return criteria.size() > 0;
	}

	public List<Criterion> getAllCriteria() {
	    return criteria;
	}

	public List<Criterion> getCriteria() {
	    return criteria;
	}

	protected void addCriterion(String condition) {
	    if (condition == null) {
		throw new RuntimeException("Value for condition cannot be null");
	    }
	    criteria.add(new Criterion(condition));
	}

	protected void addCriterion(String condition, Object value, String property) {
	    if (value == null) {
		throw new RuntimeException("Value for " + property + " cannot be null");
	    }
	    criteria.add(new Criterion(condition, value));
	}

	protected void addCriterion(String condition, Object value1, Object value2, String property) {
	    if (value1 == null || value2 == null) {
		throw new RuntimeException("Between values for " + property + " cannot be null");
	    }
	    criteria.add(new Criterion(condition, value1, value2));
	}

	public Criteria andOrderIdIsNull() {
	    addCriterion("orderId is null");
	    return (Criteria) this;
	}

	public Criteria andOrderIdIsNotNull() {
	    addCriterion("orderId is not null");
	    return (Criteria) this;
	}

	public Criteria andOrderIdEqualTo(Long value) {
	    addCriterion("orderId =", value, "orderId");
	    return (Criteria) this;
	}

	public Criteria andOrderIdNotEqualTo(Long value) {
	    addCriterion("orderId <>", value, "orderId");
	    return (Criteria) this;
	}

	public Criteria andOrderIdGreaterThan(Long value) {
	    addCriterion("orderId >", value, "orderId");
	    return (Criteria) this;
	}

	public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
	    addCriterion("orderId >=", value, "orderId");
	    return (Criteria) this;
	}

	public Criteria andOrderIdLessThan(Long value) {
	    addCriterion("orderId <", value, "orderId");
	    return (Criteria) this;
	}

	public Criteria andOrderIdLessThanOrEqualTo(Long value) {
	    addCriterion("orderId <=", value, "orderId");
	    return (Criteria) this;
	}

	public Criteria andOrderIdIn(List<Long> values) {
	    addCriterion("orderId in", values, "orderId");
	    return (Criteria) this;
	}

	public Criteria andOrderIdNotIn(List<Long> values) {
	    addCriterion("orderId not in", values, "orderId");
	    return (Criteria) this;
	}

	public Criteria andOrderIdBetween(Long value1, Long value2) {
	    addCriterion("orderId between", value1, value2, "orderId");
	    return (Criteria) this;
	}

	public Criteria andOrderIdNotBetween(Long value1, Long value2) {
	    addCriterion("orderId not between", value1, value2, "orderId");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelIsNull() {
	    addCriterion("sdkChannel is null");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelIsNotNull() {
	    addCriterion("sdkChannel is not null");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelEqualTo(Integer value) {
	    addCriterion("sdkChannel =", value, "sdkChannel");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelNotEqualTo(Integer value) {
	    addCriterion("sdkChannel <>", value, "sdkChannel");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelGreaterThan(Integer value) {
	    addCriterion("sdkChannel >", value, "sdkChannel");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelGreaterThanOrEqualTo(Integer value) {
	    addCriterion("sdkChannel >=", value, "sdkChannel");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelLessThan(Integer value) {
	    addCriterion("sdkChannel <", value, "sdkChannel");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelLessThanOrEqualTo(Integer value) {
	    addCriterion("sdkChannel <=", value, "sdkChannel");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelIn(List<Integer> values) {
	    addCriterion("sdkChannel in", values, "sdkChannel");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelNotIn(List<Integer> values) {
	    addCriterion("sdkChannel not in", values, "sdkChannel");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelBetween(Integer value1, Integer value2) {
	    addCriterion("sdkChannel between", value1, value2, "sdkChannel");
	    return (Criteria) this;
	}

	public Criteria andSdkChannelNotBetween(Integer value1, Integer value2) {
	    addCriterion("sdkChannel not between", value1, value2, "sdkChannel");
	    return (Criteria) this;
	}

	public Criteria andChannelIdIsNull() {
	    addCriterion("channelId is null");
	    return (Criteria) this;
	}

	public Criteria andChannelIdIsNotNull() {
	    addCriterion("channelId is not null");
	    return (Criteria) this;
	}

	public Criteria andChannelIdEqualTo(String value) {
	    addCriterion("channelId =", value, "channelId");
	    return (Criteria) this;
	}

	public Criteria andChannelIdNotEqualTo(String value) {
	    addCriterion("channelId <>", value, "channelId");
	    return (Criteria) this;
	}

	public Criteria andChannelIdGreaterThan(String value) {
	    addCriterion("channelId >", value, "channelId");
	    return (Criteria) this;
	}

	public Criteria andChannelIdGreaterThanOrEqualTo(String value) {
	    addCriterion("channelId >=", value, "channelId");
	    return (Criteria) this;
	}

	public Criteria andChannelIdLessThan(String value) {
	    addCriterion("channelId <", value, "channelId");
	    return (Criteria) this;
	}

	public Criteria andChannelIdLessThanOrEqualTo(String value) {
	    addCriterion("channelId <=", value, "channelId");
	    return (Criteria) this;
	}

	public Criteria andChannelIdLike(String value) {
	    addCriterion("channelId like", value, "channelId");
	    return (Criteria) this;
	}

	public Criteria andChannelIdNotLike(String value) {
	    addCriterion("channelId not like", value, "channelId");
	    return (Criteria) this;
	}

	public Criteria andChannelIdIn(List<String> values) {
	    addCriterion("channelId in", values, "channelId");
	    return (Criteria) this;
	}

	public Criteria andChannelIdNotIn(List<String> values) {
	    addCriterion("channelId not in", values, "channelId");
	    return (Criteria) this;
	}

	public Criteria andChannelIdBetween(String value1, String value2) {
	    addCriterion("channelId between", value1, value2, "channelId");
	    return (Criteria) this;
	}

	public Criteria andChannelIdNotBetween(String value1, String value2) {
	    addCriterion("channelId not between", value1, value2, "channelId");
	    return (Criteria) this;
	}

	public Criteria andServerIdIsNull() {
	    addCriterion("serverId is null");
	    return (Criteria) this;
	}

	public Criteria andServerIdIsNotNull() {
	    addCriterion("serverId is not null");
	    return (Criteria) this;
	}

	public Criteria andServerIdEqualTo(String value) {
	    addCriterion("serverId =", value, "serverId");
	    return (Criteria) this;
	}

	public Criteria andServerIdNotEqualTo(String value) {
	    addCriterion("serverId <>", value, "serverId");
	    return (Criteria) this;
	}

	public Criteria andServerIdGreaterThan(String value) {
	    addCriterion("serverId >", value, "serverId");
	    return (Criteria) this;
	}

	public Criteria andServerIdGreaterThanOrEqualTo(String value) {
	    addCriterion("serverId >=", value, "serverId");
	    return (Criteria) this;
	}

	public Criteria andServerIdLessThan(String value) {
	    addCriterion("serverId <", value, "serverId");
	    return (Criteria) this;
	}

	public Criteria andServerIdLessThanOrEqualTo(String value) {
	    addCriterion("serverId <=", value, "serverId");
	    return (Criteria) this;
	}

	public Criteria andServerIdLike(String value) {
	    addCriterion("serverId like", value, "serverId");
	    return (Criteria) this;
	}

	public Criteria andServerIdNotLike(String value) {
	    addCriterion("serverId not like", value, "serverId");
	    return (Criteria) this;
	}

	public Criteria andServerIdIn(List<String> values) {
	    addCriterion("serverId in", values, "serverId");
	    return (Criteria) this;
	}

	public Criteria andServerIdNotIn(List<String> values) {
	    addCriterion("serverId not in", values, "serverId");
	    return (Criteria) this;
	}

	public Criteria andServerIdBetween(String value1, String value2) {
	    addCriterion("serverId between", value1, value2, "serverId");
	    return (Criteria) this;
	}

	public Criteria andServerIdNotBetween(String value1, String value2) {
	    addCriterion("serverId not between", value1, value2, "serverId");
	    return (Criteria) this;
	}

	public Criteria andUserIdIsNull() {
	    addCriterion("userId is null");
	    return (Criteria) this;
	}

	public Criteria andUserIdIsNotNull() {
	    addCriterion("userId is not null");
	    return (Criteria) this;
	}

	public Criteria andUserIdEqualTo(String value) {
	    addCriterion("userId =", value, "userId");
	    return (Criteria) this;
	}

	public Criteria andUserIdNotEqualTo(String value) {
	    addCriterion("userId <>", value, "userId");
	    return (Criteria) this;
	}

	public Criteria andUserIdGreaterThan(String value) {
	    addCriterion("userId >", value, "userId");
	    return (Criteria) this;
	}

	public Criteria andUserIdGreaterThanOrEqualTo(String value) {
	    addCriterion("userId >=", value, "userId");
	    return (Criteria) this;
	}

	public Criteria andUserIdLessThan(String value) {
	    addCriterion("userId <", value, "userId");
	    return (Criteria) this;
	}

	public Criteria andUserIdLessThanOrEqualTo(String value) {
	    addCriterion("userId <=", value, "userId");
	    return (Criteria) this;
	}

	public Criteria andUserIdLike(String value) {
	    addCriterion("userId like", value, "userId");
	    return (Criteria) this;
	}

	public Criteria andUserIdNotLike(String value) {
	    addCriterion("userId not like", value, "userId");
	    return (Criteria) this;
	}

	public Criteria andUserIdIn(List<String> values) {
	    addCriterion("userId in", values, "userId");
	    return (Criteria) this;
	}

	public Criteria andUserIdNotIn(List<String> values) {
	    addCriterion("userId not in", values, "userId");
	    return (Criteria) this;
	}

	public Criteria andUserIdBetween(String value1, String value2) {
	    addCriterion("userId between", value1, value2, "userId");
	    return (Criteria) this;
	}

	public Criteria andUserIdNotBetween(String value1, String value2) {
	    addCriterion("userId not between", value1, value2, "userId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdIsNull() {
	    addCriterion("roleId is null");
	    return (Criteria) this;
	}

	public Criteria andRoleIdIsNotNull() {
	    addCriterion("roleId is not null");
	    return (Criteria) this;
	}

	public Criteria andRoleIdEqualTo(String value) {
	    addCriterion("roleId =", value, "roleId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdNotEqualTo(String value) {
	    addCriterion("roleId <>", value, "roleId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdGreaterThan(String value) {
	    addCriterion("roleId >", value, "roleId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdGreaterThanOrEqualTo(String value) {
	    addCriterion("roleId >=", value, "roleId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdLessThan(String value) {
	    addCriterion("roleId <", value, "roleId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdLessThanOrEqualTo(String value) {
	    addCriterion("roleId <=", value, "roleId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdLike(String value) {
	    addCriterion("roleId like", value, "roleId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdNotLike(String value) {
	    addCriterion("roleId not like", value, "roleId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdIn(List<String> values) {
	    addCriterion("roleId in", values, "roleId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdNotIn(List<String> values) {
	    addCriterion("roleId not in", values, "roleId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdBetween(String value1, String value2) {
	    addCriterion("roleId between", value1, value2, "roleId");
	    return (Criteria) this;
	}

	public Criteria andRoleIdNotBetween(String value1, String value2) {
	    addCriterion("roleId not between", value1, value2, "roleId");
	    return (Criteria) this;
	}

	public Criteria andProductIdIsNull() {
	    addCriterion("productId is null");
	    return (Criteria) this;
	}

	public Criteria andProductIdIsNotNull() {
	    addCriterion("productId is not null");
	    return (Criteria) this;
	}

	public Criteria andProductIdEqualTo(String value) {
	    addCriterion("productId =", value, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductIdNotEqualTo(String value) {
	    addCriterion("productId <>", value, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductIdGreaterThan(String value) {
	    addCriterion("productId >", value, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductIdGreaterThanOrEqualTo(String value) {
	    addCriterion("productId >=", value, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductIdLessThan(String value) {
	    addCriterion("productId <", value, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductIdLessThanOrEqualTo(String value) {
	    addCriterion("productId <=", value, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductIdLike(String value) {
	    addCriterion("productId like", value, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductIdNotLike(String value) {
	    addCriterion("productId not like", value, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductIdIn(List<String> values) {
	    addCriterion("productId in", values, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductIdNotIn(List<String> values) {
	    addCriterion("productId not in", values, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductIdBetween(String value1, String value2) {
	    addCriterion("productId between", value1, value2, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductIdNotBetween(String value1, String value2) {
	    addCriterion("productId not between", value1, value2, "productId");
	    return (Criteria) this;
	}

	public Criteria andProductAmountIsNull() {
	    addCriterion("productAmount is null");
	    return (Criteria) this;
	}

	public Criteria andProductAmountIsNotNull() {
	    addCriterion("productAmount is not null");
	    return (Criteria) this;
	}

	public Criteria andProductAmountEqualTo(Integer value) {
	    addCriterion("productAmount =", value, "productAmount");
	    return (Criteria) this;
	}

	public Criteria andProductAmountNotEqualTo(Integer value) {
	    addCriterion("productAmount <>", value, "productAmount");
	    return (Criteria) this;
	}

	public Criteria andProductAmountGreaterThan(Integer value) {
	    addCriterion("productAmount >", value, "productAmount");
	    return (Criteria) this;
	}

	public Criteria andProductAmountGreaterThanOrEqualTo(Integer value) {
	    addCriterion("productAmount >=", value, "productAmount");
	    return (Criteria) this;
	}

	public Criteria andProductAmountLessThan(Integer value) {
	    addCriterion("productAmount <", value, "productAmount");
	    return (Criteria) this;
	}

	public Criteria andProductAmountLessThanOrEqualTo(Integer value) {
	    addCriterion("productAmount <=", value, "productAmount");
	    return (Criteria) this;
	}

	public Criteria andProductAmountIn(List<Integer> values) {
	    addCriterion("productAmount in", values, "productAmount");
	    return (Criteria) this;
	}

	public Criteria andProductAmountNotIn(List<Integer> values) {
	    addCriterion("productAmount not in", values, "productAmount");
	    return (Criteria) this;
	}

	public Criteria andProductAmountBetween(Integer value1, Integer value2) {
	    addCriterion("productAmount between", value1, value2, "productAmount");
	    return (Criteria) this;
	}

	public Criteria andProductAmountNotBetween(Integer value1, Integer value2) {
	    addCriterion("productAmount not between", value1, value2, "productAmount");
	    return (Criteria) this;
	}

	public Criteria andProductNumIsNull() {
	    addCriterion("productNum is null");
	    return (Criteria) this;
	}

	public Criteria andProductNumIsNotNull() {
	    addCriterion("productNum is not null");
	    return (Criteria) this;
	}

	public Criteria andProductNumEqualTo(Integer value) {
	    addCriterion("productNum =", value, "productNum");
	    return (Criteria) this;
	}

	public Criteria andProductNumNotEqualTo(Integer value) {
	    addCriterion("productNum <>", value, "productNum");
	    return (Criteria) this;
	}

	public Criteria andProductNumGreaterThan(Integer value) {
	    addCriterion("productNum >", value, "productNum");
	    return (Criteria) this;
	}

	public Criteria andProductNumGreaterThanOrEqualTo(Integer value) {
	    addCriterion("productNum >=", value, "productNum");
	    return (Criteria) this;
	}

	public Criteria andProductNumLessThan(Integer value) {
	    addCriterion("productNum <", value, "productNum");
	    return (Criteria) this;
	}

	public Criteria andProductNumLessThanOrEqualTo(Integer value) {
	    addCriterion("productNum <=", value, "productNum");
	    return (Criteria) this;
	}

	public Criteria andProductNumIn(List<Integer> values) {
	    addCriterion("productNum in", values, "productNum");
	    return (Criteria) this;
	}

	public Criteria andProductNumNotIn(List<Integer> values) {
	    addCriterion("productNum not in", values, "productNum");
	    return (Criteria) this;
	}

	public Criteria andProductNumBetween(Integer value1, Integer value2) {
	    addCriterion("productNum between", value1, value2, "productNum");
	    return (Criteria) this;
	}

	public Criteria andProductNumNotBetween(Integer value1, Integer value2) {
	    addCriterion("productNum not between", value1, value2, "productNum");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyIsNull() {
	    addCriterion("virtualCurrency is null");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyIsNotNull() {
	    addCriterion("virtualCurrency is not null");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyEqualTo(Integer value) {
	    addCriterion("virtualCurrency =", value, "virtualCurrency");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyNotEqualTo(Integer value) {
	    addCriterion("virtualCurrency <>", value, "virtualCurrency");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyGreaterThan(Integer value) {
	    addCriterion("virtualCurrency >", value, "virtualCurrency");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyGreaterThanOrEqualTo(Integer value) {
	    addCriterion("virtualCurrency >=", value, "virtualCurrency");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyLessThan(Integer value) {
	    addCriterion("virtualCurrency <", value, "virtualCurrency");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyLessThanOrEqualTo(Integer value) {
	    addCriterion("virtualCurrency <=", value, "virtualCurrency");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyIn(List<Integer> values) {
	    addCriterion("virtualCurrency in", values, "virtualCurrency");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyNotIn(List<Integer> values) {
	    addCriterion("virtualCurrency not in", values, "virtualCurrency");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyBetween(Integer value1, Integer value2) {
	    addCriterion("virtualCurrency between", value1, value2, "virtualCurrency");
	    return (Criteria) this;
	}

	public Criteria andVirtualCurrencyNotBetween(Integer value1, Integer value2) {
	    addCriterion("virtualCurrency not between", value1, value2, "virtualCurrency");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoIsNull() {
	    addCriterion("orderInfo is null");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoIsNotNull() {
	    addCriterion("orderInfo is not null");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoEqualTo(String value) {
	    addCriterion("orderInfo =", value, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoNotEqualTo(String value) {
	    addCriterion("orderInfo <>", value, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoGreaterThan(String value) {
	    addCriterion("orderInfo >", value, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoGreaterThanOrEqualTo(String value) {
	    addCriterion("orderInfo >=", value, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoLessThan(String value) {
	    addCriterion("orderInfo <", value, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoLessThanOrEqualTo(String value) {
	    addCriterion("orderInfo <=", value, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoLike(String value) {
	    addCriterion("orderInfo like", value, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoNotLike(String value) {
	    addCriterion("orderInfo not like", value, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoIn(List<String> values) {
	    addCriterion("orderInfo in", values, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoNotIn(List<String> values) {
	    addCriterion("orderInfo not in", values, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoBetween(String value1, String value2) {
	    addCriterion("orderInfo between", value1, value2, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderInfoNotBetween(String value1, String value2) {
	    addCriterion("orderInfo not between", value1, value2, "orderInfo");
	    return (Criteria) this;
	}

	public Criteria andOrderExtIsNull() {
	    addCriterion("orderExt is null");
	    return (Criteria) this;
	}

	public Criteria andOrderExtIsNotNull() {
	    addCriterion("orderExt is not null");
	    return (Criteria) this;
	}

	public Criteria andOrderExtEqualTo(String value) {
	    addCriterion("orderExt =", value, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderExtNotEqualTo(String value) {
	    addCriterion("orderExt <>", value, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderExtGreaterThan(String value) {
	    addCriterion("orderExt >", value, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderExtGreaterThanOrEqualTo(String value) {
	    addCriterion("orderExt >=", value, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderExtLessThan(String value) {
	    addCriterion("orderExt <", value, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderExtLessThanOrEqualTo(String value) {
	    addCriterion("orderExt <=", value, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderExtLike(String value) {
	    addCriterion("orderExt like", value, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderExtNotLike(String value) {
	    addCriterion("orderExt not like", value, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderExtIn(List<String> values) {
	    addCriterion("orderExt in", values, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderExtNotIn(List<String> values) {
	    addCriterion("orderExt not in", values, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderExtBetween(String value1, String value2) {
	    addCriterion("orderExt between", value1, value2, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderExtNotBetween(String value1, String value2) {
	    addCriterion("orderExt not between", value1, value2, "orderExt");
	    return (Criteria) this;
	}

	public Criteria andOrderStateIsNull() {
	    addCriterion("orderState is null");
	    return (Criteria) this;
	}

	public Criteria andOrderStateIsNotNull() {
	    addCriterion("orderState is not null");
	    return (Criteria) this;
	}

	public Criteria andOrderStateEqualTo(Integer value) {
	    addCriterion("orderState =", value, "orderState");
	    return (Criteria) this;
	}

	public Criteria andOrderStateNotEqualTo(Integer value) {
	    addCriterion("orderState <>", value, "orderState");
	    return (Criteria) this;
	}

	public Criteria andOrderStateGreaterThan(Integer value) {
	    addCriterion("orderState >", value, "orderState");
	    return (Criteria) this;
	}

	public Criteria andOrderStateGreaterThanOrEqualTo(Integer value) {
	    addCriterion("orderState >=", value, "orderState");
	    return (Criteria) this;
	}

	public Criteria andOrderStateLessThan(Integer value) {
	    addCriterion("orderState <", value, "orderState");
	    return (Criteria) this;
	}

	public Criteria andOrderStateLessThanOrEqualTo(Integer value) {
	    addCriterion("orderState <=", value, "orderState");
	    return (Criteria) this;
	}

	public Criteria andOrderStateIn(List<Integer> values) {
	    addCriterion("orderState in", values, "orderState");
	    return (Criteria) this;
	}

	public Criteria andOrderStateNotIn(List<Integer> values) {
	    addCriterion("orderState not in", values, "orderState");
	    return (Criteria) this;
	}

	public Criteria andOrderStateBetween(Integer value1, Integer value2) {
	    addCriterion("orderState between", value1, value2, "orderState");
	    return (Criteria) this;
	}

	public Criteria andOrderStateNotBetween(Integer value1, Integer value2) {
	    addCriterion("orderState not between", value1, value2, "orderState");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeIsNull() {
	    addCriterion("createTime is null");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeIsNotNull() {
	    addCriterion("createTime is not null");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeEqualTo(Long value) {
	    addCriterion("createTime =", value, "createTime");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeNotEqualTo(Long value) {
	    addCriterion("createTime <>", value, "createTime");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeGreaterThan(Long value) {
	    addCriterion("createTime >", value, "createTime");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
	    addCriterion("createTime >=", value, "createTime");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeLessThan(Long value) {
	    addCriterion("createTime <", value, "createTime");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
	    addCriterion("createTime <=", value, "createTime");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeIn(List<Long> values) {
	    addCriterion("createTime in", values, "createTime");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeNotIn(List<Long> values) {
	    addCriterion("createTime not in", values, "createTime");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeBetween(Long value1, Long value2) {
	    addCriterion("createTime between", value1, value2, "createTime");
	    return (Criteria) this;
	}

	public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
	    addCriterion("createTime not between", value1, value2, "createTime");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateIsNull() {
	    addCriterion("dispatchState is null");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateIsNotNull() {
	    addCriterion("dispatchState is not null");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateEqualTo(Integer value) {
	    addCriterion("dispatchState =", value, "dispatchState");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateNotEqualTo(Integer value) {
	    addCriterion("dispatchState <>", value, "dispatchState");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateGreaterThan(Integer value) {
	    addCriterion("dispatchState >", value, "dispatchState");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateGreaterThanOrEqualTo(Integer value) {
	    addCriterion("dispatchState >=", value, "dispatchState");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateLessThan(Integer value) {
	    addCriterion("dispatchState <", value, "dispatchState");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateLessThanOrEqualTo(Integer value) {
	    addCriterion("dispatchState <=", value, "dispatchState");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateIn(List<Integer> values) {
	    addCriterion("dispatchState in", values, "dispatchState");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateNotIn(List<Integer> values) {
	    addCriterion("dispatchState not in", values, "dispatchState");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateBetween(Integer value1, Integer value2) {
	    addCriterion("dispatchState between", value1, value2, "dispatchState");
	    return (Criteria) this;
	}

	public Criteria andDispatchStateNotBetween(Integer value1, Integer value2) {
	    addCriterion("dispatchState not between", value1, value2, "dispatchState");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeIsNull() {
	    addCriterion("dispatchTime is null");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeIsNotNull() {
	    addCriterion("dispatchTime is not null");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeEqualTo(Long value) {
	    addCriterion("dispatchTime =", value, "dispatchTime");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeNotEqualTo(Long value) {
	    addCriterion("dispatchTime <>", value, "dispatchTime");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeGreaterThan(Long value) {
	    addCriterion("dispatchTime >", value, "dispatchTime");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeGreaterThanOrEqualTo(Long value) {
	    addCriterion("dispatchTime >=", value, "dispatchTime");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeLessThan(Long value) {
	    addCriterion("dispatchTime <", value, "dispatchTime");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeLessThanOrEqualTo(Long value) {
	    addCriterion("dispatchTime <=", value, "dispatchTime");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeIn(List<Long> values) {
	    addCriterion("dispatchTime in", values, "dispatchTime");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeNotIn(List<Long> values) {
	    addCriterion("dispatchTime not in", values, "dispatchTime");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeBetween(Long value1, Long value2) {
	    addCriterion("dispatchTime between", value1, value2, "dispatchTime");
	    return (Criteria) this;
	}

	public Criteria andDispatchTimeNotBetween(Long value1, Long value2) {
	    addCriterion("dispatchTime not between", value1, value2, "dispatchTime");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountIsNull() {
	    addCriterion("dispatchCount is null");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountIsNotNull() {
	    addCriterion("dispatchCount is not null");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountEqualTo(Integer value) {
	    addCriterion("dispatchCount =", value, "dispatchCount");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountNotEqualTo(Integer value) {
	    addCriterion("dispatchCount <>", value, "dispatchCount");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountGreaterThan(Integer value) {
	    addCriterion("dispatchCount >", value, "dispatchCount");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountGreaterThanOrEqualTo(Integer value) {
	    addCriterion("dispatchCount >=", value, "dispatchCount");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountLessThan(Integer value) {
	    addCriterion("dispatchCount <", value, "dispatchCount");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountLessThanOrEqualTo(Integer value) {
	    addCriterion("dispatchCount <=", value, "dispatchCount");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountIn(List<Integer> values) {
	    addCriterion("dispatchCount in", values, "dispatchCount");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountNotIn(List<Integer> values) {
	    addCriterion("dispatchCount not in", values, "dispatchCount");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountBetween(Integer value1, Integer value2) {
	    addCriterion("dispatchCount between", value1, value2, "dispatchCount");
	    return (Criteria) this;
	}

	public Criteria andDispatchCountNotBetween(Integer value1, Integer value2) {
	    addCriterion("dispatchCount not between", value1, value2, "dispatchCount");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeIsNull() {
	    addCriterion("nextDispatchTime is null");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeIsNotNull() {
	    addCriterion("nextDispatchTime is not null");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeEqualTo(Long value) {
	    addCriterion("nextDispatchTime =", value, "nextDispatchTime");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeNotEqualTo(Long value) {
	    addCriterion("nextDispatchTime <>", value, "nextDispatchTime");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeGreaterThan(Long value) {
	    addCriterion("nextDispatchTime >", value, "nextDispatchTime");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeGreaterThanOrEqualTo(Long value) {
	    addCriterion("nextDispatchTime >=", value, "nextDispatchTime");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeLessThan(Long value) {
	    addCriterion("nextDispatchTime <", value, "nextDispatchTime");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeLessThanOrEqualTo(Long value) {
	    addCriterion("nextDispatchTime <=", value, "nextDispatchTime");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeIn(List<Long> values) {
	    addCriterion("nextDispatchTime in", values, "nextDispatchTime");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeNotIn(List<Long> values) {
	    addCriterion("nextDispatchTime not in", values, "nextDispatchTime");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeBetween(Long value1, Long value2) {
	    addCriterion("nextDispatchTime between", value1, value2, "nextDispatchTime");
	    return (Criteria) this;
	}

	public Criteria andNextDispatchTimeNotBetween(Long value1, Long value2) {
	    addCriterion("nextDispatchTime not between", value1, value2, "nextDispatchTime");
	    return (Criteria) this;
	}

	public Criteria andPaydesIsNull() {
	    addCriterion("paydes is null");
	    return (Criteria) this;
	}

	public Criteria andPaydesIsNotNull() {
	    addCriterion("paydes is not null");
	    return (Criteria) this;
	}

	public Criteria andPaydesEqualTo(String value) {
	    addCriterion("paydes =", value, "paydes");
	    return (Criteria) this;
	}

	public Criteria andPaydesNotEqualTo(String value) {
	    addCriterion("paydes <>", value, "paydes");
	    return (Criteria) this;
	}

	public Criteria andPaydesGreaterThan(String value) {
	    addCriterion("paydes >", value, "paydes");
	    return (Criteria) this;
	}

	public Criteria andPaydesGreaterThanOrEqualTo(String value) {
	    addCriterion("paydes >=", value, "paydes");
	    return (Criteria) this;
	}

	public Criteria andPaydesLessThan(String value) {
	    addCriterion("paydes <", value, "paydes");
	    return (Criteria) this;
	}

	public Criteria andPaydesLessThanOrEqualTo(String value) {
	    addCriterion("paydes <=", value, "paydes");
	    return (Criteria) this;
	}

	public Criteria andPaydesLike(String value) {
	    addCriterion("paydes like", value, "paydes");
	    return (Criteria) this;
	}

	public Criteria andPaydesNotLike(String value) {
	    addCriterion("paydes not like", value, "paydes");
	    return (Criteria) this;
	}

	public Criteria andPaydesIn(List<String> values) {
	    addCriterion("paydes in", values, "paydes");
	    return (Criteria) this;
	}

	public Criteria andPaydesNotIn(List<String> values) {
	    addCriterion("paydes not in", values, "paydes");
	    return (Criteria) this;
	}

	public Criteria andPaydesBetween(String value1, String value2) {
	    addCriterion("paydes between", value1, value2, "paydes");
	    return (Criteria) this;
	}

	public Criteria andPaydesNotBetween(String value1, String value2) {
	    addCriterion("paydes not between", value1, value2, "paydes");
	    return (Criteria) this;
	}
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_order
     * @mbggenerated
     */
    public static class Criterion {
	private String condition;
	private Object value;
	private Object secondValue;
	private boolean noValue;
	private boolean singleValue;
	private boolean betweenValue;
	private boolean listValue;
	private String typeHandler;

	public String getCondition() {
	    return condition;
	}

	public Object getValue() {
	    return value;
	}

	public Object getSecondValue() {
	    return secondValue;
	}

	public boolean isNoValue() {
	    return noValue;
	}

	public boolean isSingleValue() {
	    return singleValue;
	}

	public boolean isBetweenValue() {
	    return betweenValue;
	}

	public boolean isListValue() {
	    return listValue;
	}

	public String getTypeHandler() {
	    return typeHandler;
	}

	protected Criterion(String condition) {
	    super();
	    this.condition = condition;
	    this.typeHandler = null;
	    this.noValue = true;
	}

	protected Criterion(String condition, Object value, String typeHandler) {
	    super();
	    this.condition = condition;
	    this.value = value;
	    this.typeHandler = typeHandler;
	    if (value instanceof List<?>) {
		this.listValue = true;
	    } else {
		this.singleValue = true;
	    }
	}

	protected Criterion(String condition, Object value) {
	    this(condition, value, null);
	}

	protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
	    super();
	    this.condition = condition;
	    this.value = value;
	    this.secondValue = secondValue;
	    this.typeHandler = typeHandler;
	    this.betweenValue = true;
	}

	protected Criterion(String condition, Object value, Object secondValue) {
	    this(condition, value, secondValue, null);
	}
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}