package com.server.db.model;

public class ProductRecord {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_product.uid
     * @mbggenerated
     */
    private Long uid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_product.channelId
     * @mbggenerated
     */
    private String channelId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_product.productId
     * @mbggenerated
     */
    private String productId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_product.rmb
     * @mbggenerated
     */
    private Integer rmb;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_product.virtualCurrency
     * @mbggenerated
     */
    private Integer virtualCurrency;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_product.uid
     * @return  the value of t_product.uid
     * @mbggenerated
     */
    public Long getUid() {
	return uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_product.uid
     * @param uid  the value for t_product.uid
     * @mbggenerated
     */
    public void setUid(Long uid) {
	this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_product.channelId
     * @return  the value of t_product.channelId
     * @mbggenerated
     */
    public String getChannelId() {
	return channelId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_product.channelId
     * @param channelId  the value for t_product.channelId
     * @mbggenerated
     */
    public void setChannelId(String channelId) {
	this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_product.productId
     * @return  the value of t_product.productId
     * @mbggenerated
     */
    public String getProductId() {
	return productId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_product.productId
     * @param productId  the value for t_product.productId
     * @mbggenerated
     */
    public void setProductId(String productId) {
	this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_product.rmb
     * @return  the value of t_product.rmb
     * @mbggenerated
     */
    public Integer getRmb() {
	return rmb;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_product.rmb
     * @param rmb  the value for t_product.rmb
     * @mbggenerated
     */
    public void setRmb(Integer rmb) {
	this.rmb = rmb;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_product.virtualCurrency
     * @return  the value of t_product.virtualCurrency
     * @mbggenerated
     */
    public Integer getVirtualCurrency() {
	return virtualCurrency;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_product.virtualCurrency
     * @param virtualCurrency  the value for t_product.virtualCurrency
     * @mbggenerated
     */
    public void setVirtualCurrency(Integer virtualCurrency) {
	this.virtualCurrency = virtualCurrency;
    }
}